//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public long Id { get; set; }
        public string Fname { get; set; }
        public string LName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public long Country { get; set; }
        public long State { get; set; }
        public long City { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string TeacherId { get; set; }
    }
}
